Iterate based on feedback

diff --git a/test/unit b/test/unit
--- a/test/unit
+++ b/test/unit
@@ -70,15 +70,6 @@ testKeyValueEscaping() {
 
 # if the file doesn't exist, everything should be a no-op
 testKeyValueNoFile() {
-  # empty file argument
-  local empty=""
-
-  kv_set $empty key value
-
-  assertEquals "$(kv_get $empty key)" ""
-  assertEquals "$(kv_keys $empty)" ""
-  assertEquals "$(kv_list $empty)" ""
-
   local store="/tmp/does-not-exist"
 
   kv_set "$store" key value
@@ -89,15 +80,97 @@ testKeyValueNoFile() {
 
   # running these commands has not created this file
   assertTrue "[[ ! -e $store ]]"
-
-  local space=" "
-  kv_set "$space" key value
-
-  assertEquals "$(kv_get "$space" key)" ""
-  assertEquals "$(kv_keys "$space")" ""
-  assertEquals "$(kv_list "$space")" ""
 }
 
+testKeyValueMultiLineString() {
+  local store value
+
+  store=$(mktemp)
+
+  kv_create "$store"
+
+  # create a multi-line string
+  read -r -d '' value << EOM
+This is line 1.
+This is line 2.
+Line 3.
+EOM
+
+  kv_set "$store" key "$value"
+
+  # the value will be flattened into one line
+  assertEquals "$(kv_get "$store" key)" "This is line 1. This is line 2. Line 3."
+}
+
+testKeyValueStringWithQuotes() {
+  local store value build script
+
+  store=$(mktemp)
+
+  kv_create "$store"
+
+  value="echo \"foo\" bar"
+  build="node -e \"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'vendor/assets/bower_components', 'junction') } catch (e) { }\""
+  script="if test \"\$NODE_ENV\" = \"production\"; then webpack --config webpack/webpack.config.prod.js; fi"
+
+  kv_set "$store" key "$value"
+  kv_set "$store" build "$build"
+  kv_set "$store" script "$script"
+
+  assertEquals "$(kv_get "$store" key)" "$value"
+  assertEquals "$(kv_get_escaped "$store" key)" "\"echo \\\"foo\\\" bar\""
+
+  assertEquals "$(kv_get "$store" build)" "$build"
+  assertEquals "$(kv_get_escaped "$store" build)" "\"node -e \\\"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'vendor/assets/bower_components', 'junction') } catch (e) { }\\\"\""
+
+  assertEquals "$(kv_get "$store" script)" "$script"
+  assertEquals "$(kv_get_escaped "$store" script)" "\"if test \\\"\$NODE_ENV\\\" = \\\"production\\\"; then webpack --config webpack/webpack.config.prod.js; fi\""
+}
+
+# Keys must match [a-zA-Z_][a-zA-Z0-9_]+
+testKeyNameEnforcement() {
+  local store value out
+
+  store=$(mktemp)
+
+  kv_create "$store"
+
+  out=$(kv_set "$store" "@foo" "value" 2>&1)
+  # assert that the exit code was 0
+  assertEquals "1" "$?"
+  # assert the error message
+  assertEquals "invalid param to kv_set '@foo'" "$out"
+
+  out=$(kv_set "$store" "123" "value" 2>&1)
+  # assert that the exit code was 0
+  assertEquals "1" "$?"
+  # assert the error message
+  assertEquals "invalid param to kv_set '123'" "$out"
+}
+
+testKeyValueErrors() {
+  local store value out
+
+  store=$(mktemp)
+
+  kv_create "$store"
+
+  # an empty value string shouldn't fail
+  out=$(kv_set "$store" "key" "" 2>&1)
+  assertEquals "0" "$?"
+
+  out=$(kv_set "$store" "key-with-no-value" 2>&1)
+  assertEquals "1" "$?"
+  assertEquals "Expected 3 arguments to kv_set, received 2" "$out"
+
+  out=$(kv_set "$store" 2>&1)
+  assertEquals "1" "$?"
+  assertEquals "Expected 3 arguments to kv_set, received 1" "$out"
+
+  out=$(kv_get "$store" 2>&1)
+  assertEquals "1" "$?"
+  assertEquals "Expected 2 arguments to kv_get, received 1" "$out"
+}
 
 # the module to be tested
 # shellcheck source=stdlib.sh
